config/routes.rb
Rails.application.routes.draw do
  resources :vendors
  get 'ajax_calls/check_email_taken'
  get 'ajax_calls/category_products'
  get 'ajax_calls/find_sub_categories'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'products/index'
  get 'home/about'
  get 'home/contact'
  get 'reviews/index'
  get 'wishlists/index'
  
  resources :orders
  resources :addresses
resources :cart_line_items
resources :reviews
resources :wishlists
  resources :products, :categories, :users
  root 'categories#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
	has_many :orders
	validates_presence_of :user_id, :street, :pin, :city,:landmark
	validates_numericality_of :user_id, :pin
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name,:acc_no,:balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no

	def transaction(code,amount)
		if code == 0
			if self.balance - amount < 0
				puts "Insufficient Funds"
			else
			self.balance = self.balance-amount
			self.update_attributes(balance: self.balance)
		end
	else
		self.balance += amount
		self.update_attributes(balance:self.balance)
	end
end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_many :wishlists
	has_many :orders
	
	validates_presence_of :user_id, :product_id,:quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity,within: 1..10


	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id,product_id: self.product_id)

		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
		
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_line_items
	belongs_to :address
	validates_presence_of :user_id, :order_number, :order_date
	

	#call back
	after_create :copy_cart_line_items_to_line_items
	after_create :empty_cart_line_items
	after_create :calc_total
	# after_create :order_confirmation
	
	def copy_cart_line_items_to_line_items
		user = self.user
		user.cart_line_items.each do |line_item|
			order_line_item = OrderLineItem.new
			order_line_item.product_id = line_item.product_id
			order_line_item.quantity = line_item.quantity
			order_line_item.price =  line_item.product.price
			order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = 	self.id
		order_line_item.save
	end
	end

	def empty_cart_line_items
		user =self.user
		CartLineItem.delete(user.cart_line_items.pluck(:id))
	end
	def calc_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end

	
	
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	belongs_to :order 
	belongs_to :product
	
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :sub_category
	has_many :reviews
	has_many :cart_line_items
	has_many :wishlists
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1

end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :product
belongs_to :user
validates_presence_of :user_id,:product_id,:body, :rating
validates_numericality_of :user_id,:product_id, rating: 1..5

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :cart_line_items
 	has_many :wishlists
 	has_many :orders
 	has_many :addresses
 	validates_presence_of :username, :email, :mobile, :password, :dob,:gender
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	validates_presence_of :name,:mobile,:email
	validates_uniqueness_of :mobile,:email
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	belongs_to :cart_line_item
	validates_presence_of :user_id, :product_id
	validates_numericality_of :user_id, :product_id
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  
  def index
  	@categories = Category.all 			
  	# <!--order('name AESC')-->
  	@products = Product.all
  end
  
  # def contact
  # end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/home/about.html.erb
<h2> About Us</h2>


 
<a href="/home/index"> Home </a>

<%= link_to "Home (ror)", home_index_path %>
<!-- home_index_path returns a string "/home/index" -->
<%= link_to "Contact Us", home_contact_path %>

app/views/home/contact.html.erb


<h2 >7899193782</h2>
<p><img src="G:\my photos\mine\20161201_160501.jpg" height="150px" width="150px"/></p>
<%= link_to "Home", home_index_path %>





app/views/home/index.html.erb
<h1>Home#index</h1>
<!--
<%= %> is embedded ruby tag inside that html used for presentation
<% %> is embedded ruby tag inside html used for evaluation
-->
2 + 2 : <%= 2 + 2 %> <!-- commenting -->
<% names = ["hari", "ganesh", "veeresh", "ramesh"]%>

<ul> <!-- unordered list with bullets-->
<li> Virat </li>
<li> Roshit </li>
<li> Dhoni</li>
</ul>

<ol> <!-- ordered list with numbers -->
<li> Apple</li>
<li> Samsung</li>
<li> Mi</li>
</ol>
 <h3>Listing Names</h3>
 <ol>
 	<% names.each do |name| %>
 	<li> <%= name.capitalize %></li>
 	<% end %>
 </ol>

 <%companies = [] %>
 <% if companies.empty? %>
 <p> <h1>Companies not Found</h1></p>
 <% else %>
 <h3>Listing Companies</h3>
 <ol>
 	<% companies.each do |company| %>
 	<li><%=company %></li>
 	<%end%>
 </ol>
 <%end%>

 <a href="about"> About</a>
 <%= link_to "About (ror)", home_about_path %>\
  <%= link_to "contact", home_contact_path %>

 <h2>Listing Categories</h2>
<ol>
	<% @categories.each do |category| %>
		<li><%= category.name %></li>
	<%end%>
</ol>

<h2> Listing Products</h2>
<ol>
	<% @products.each do |product| %>
	<li><%= product.name %></li>
	<%end%>
</ol>