config/routes.rb
Rails.application.routes.draw do
  resources :vendors
  get 'ajax_calls/check_email_taken'
  get 'ajax_calls/category_products'
  get 'ajax_calls/find_sub_categories'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'products/index'
  get 'home/about'
  get 'home/contact'
  get 'reviews/index'
  get 'wishlists/index'
  
  resources :orders
  resources :addresses
resources :cart_line_items
resources :reviews
resources :wishlists
  resources :products, :categories, :users
  root 'categories#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
	has_many :orders
	validates_presence_of :user_id, :street, :pin, :city,:landmark
	validates_numericality_of :user_id, :pin
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name,:acc_no,:balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0
	validates_uniqueness_of :acc_no

	def transaction(code,amount)
		if code == 0
			if self.balance - amount < 0
				puts "Insufficient Funds"
			else
			self.balance = self.balance-amount
			self.update_attributes(balance: self.balance)
		end
	else
		self.balance += amount
		self.update_attributes(balance:self.balance)
	end
end
end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_many :wishlists
	has_many :orders
	
	validates_presence_of :user_id, :product_id,:quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity,within: 1..10


	def save_or_update
		line_item = CartLineItem.find_by(user_id: self.user_id,product_id: self.product_id)

		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity: line_item.quantity + self.quantity)
		end
		
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_line_items
	belongs_to :address
	validates_presence_of :user_id, :order_number, :order_date
	

	#call back
	after_create :copy_cart_line_items_to_line_items
	after_create :empty_cart_line_items
	after_create :calc_total
	# after_create :order_confirmation
	
	def copy_cart_line_items_to_line_items
		user = self.user
		user.cart_line_items.each do |line_item|
			order_line_item = OrderLineItem.new
			order_line_item.product_id = line_item.product_id
			order_line_item.quantity = line_item.quantity
			order_line_item.price =  line_item.product.price
			order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = 	self.id
		order_line_item.save
	end
	end

	def empty_cart_line_items
		user =self.user
		CartLineItem.delete(user.cart_line_items.pluck(:id))
	end
	def calc_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end

	
	
end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
	belongs_to :order 
	belongs_to :product
	
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	belongs_to :sub_category
	has_many :reviews
	has_many :cart_line_items
	has_many :wishlists
	validates_presence_of :name, :price, :category_id, :description
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1

end

app/models/review.rb
class Review < ActiveRecord::Base
belongs_to :product
belongs_to :user
validates_presence_of :user_id,:product_id,:body, :rating
validates_numericality_of :user_id,:product_id, rating: 1..5

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :cart_line_items
 	has_many :wishlists
 	has_many :orders
 	has_many :addresses
 	validates_presence_of :username, :email, :mobile, :password, :dob,:gender
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	validates_presence_of :name,:mobile,:email
	validates_uniqueness_of :mobile,:email
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	belongs_to :cart_line_item
	validates_presence_of :user_id, :product_id
	validates_numericality_of :user_id, :product_id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
before_action :check_is_admin, except: [:index,:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    # @products = Product.where('category_id =?', @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>

<%= form_for @category do |c| %>

	<% if @category.errors.any? %>
	<h3> The Errors </h3>
	<ul>
		<% @category.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<label>Name :</label><br/>
	<%= c.text_field :name, placeholder: "Enter the category name", autofocus: true %>

	<%= c.submit %> or <%= link_to "back", categories_path %>

<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Categories</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td>
        <%= link_to category.name, category %> (<%= Product.where('category_id = ?', category.id).length%>)
        </td>
       <!--  <td><%= link_to 'Show', category %></td> -->
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
  <h2>Listing products (<%= @category.products.length %>)</h2>
  <ul>
  	<% @category.products.each do |product| %>
  		<li><%= link_to product.name, product_path(product.id)%> of INR <%= product.price %>

  		</li>
  		<% end %>
  </ul>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>